# Generated by Django 4.1.2 on 2022-11-10 11:25

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('S1', 'Secondary_1'), ('S2', 'Secondary_2'), ('S3', 'Secondary_3'), ('S4', 'Secondary_4'), ('PU1', 'PreU_1'), ('PU2', 'PreU_2')], max_length=3)),
                ('photo1', models.ImageField(max_length=500, upload_to=webapp.models.Rename.save)),
                ('photo2', models.ImageField(blank=True, max_length=500, upload_to=webapp.models.Rename.save)),
                ('photo3', models.ImageField(blank=True, max_length=500, upload_to=webapp.models.Rename.save)),
                ('encoding1', models.BinaryField(blank=True, null=True)),
                ('encoding2', models.BinaryField(blank=True, null=True)),
                ('encoding3', models.BinaryField(blank=True, null=True)),
                ('photoUI', models.ImageField(blank=True, editable=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('late_students', models.ManyToManyField(to='webapp.student_profile')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('presence', models.BooleanField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student_profile')),
            ],
        ),
    ]
