# Generated by Django 4.1 on 2022-09-13 09:41

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('late_students', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='face_encodings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('encoding1', models.BinaryField()),
                ('encoding2', models.BinaryField(blank=True)),
                ('encoding3', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('presence', models.BooleanField(default=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('photo1', models.ImageField(upload_to=webapp.models.Rename.save)),
                ('photo2', models.ImageField(blank=True, upload_to=webapp.models.Rename.save)),
                ('photo3', models.ImageField(blank=True, upload_to=webapp.models.Rename.save)),
            ],
        ),
        migrations.CreateModel(
            name='PreU_1',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
        migrations.CreateModel(
            name='PreU_2',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
        migrations.CreateModel(
            name='Secondary_1',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
        migrations.CreateModel(
            name='Secondary_2',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
        migrations.CreateModel(
            name='Secondary_3',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
        migrations.CreateModel(
            name='Secondary_4',
            fields=[
                ('student_face_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.student_face')),
            ],
            bases=('webapp.student_face',),
        ),
    ]
