# Generated by Django 4.1 on 2022-09-11 08:22

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_face',
            name='photo1',
            field=models.ImageField(upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_face',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_face',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
    ]
