# Generated by Django 4.1 on 2022-10-01 15:33

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='encoding1',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='encoding2',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='encoding3',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo1',
            field=models.ImageField(upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
    ]
