# Generated by Django 4.1 on 2022-09-25 15:11

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_student_profile_status_alter_student_profile_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo1',
            field=models.ImageField(upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=webapp.models.Rename.save),
        ),
    ]
